Invite link
cmu-sei/Alloy.Api pull request #17
Opened 2021-05-18 13:23 UTC by sei-noconnor

2021-05-18 18:12 UTC, sei-tspencer approved these changes

2021-05-18 18:28 UTC, sei-ebram commented
You mentioned about squashing the commits but you don't have to, that'll automatically happen when we merge.
Also, I noticed that you used 2-space indents but our standard convention is 4

2021-05-18 20:07 UTC, sei-aschlackman commented
> You mentioned about squashing the commits but you don't have to, that'll automatically happen when we merge.
> Also, I noticed that you used 2-space indents but our standard convention is 4

Yes, please change the indents to 4 spaces. It's hard to parse the diffs with all the indentation changes.

2021-05-18 20:09 UTC, sei-aschlackman requested changes

2021-05-18 20:09 UTC, sei-aschlackman commented on Alloy.Api/Hubs/EventHub.cs
> +    public async Task JoinEvent(Guid eventId)
All these Join methods should have some sort of permissions check.

2021-05-21 14:20 UTC, sei-aschlackman approved these changes

2021-05-21 15:51 UTC, merged